### ISSUE TITLE
[B] Work Room Sort Hanging

### ISSUE THREAD

**Issue by arialp** [BellCubeDev/AdditionalClockwork#33]
# **What Happened**

It seems like if there is a lot of a single item, the sorting system hangs for a very long time. This happened to me with the work room sorting but I'm sure that this might also happen with any room. 79 lockpicks took about 1 minute and 22k septims would take about 4 and a half hours in my condition. And during this period the button or scale used to sort these items become unusable and any items that haven't been sorted yet stay in the inventory. F5 then F9 and quitting the game then retrying doesn't fix the hang but reloading an older save fixes it.

## **Reproducing**

1. Have a lot of gold (22k in my case)
2. Go to the work room (possibly any room)
3. Use the sorting scale

# **Expected behavior**

Expected the sorting system to skip the item if it's not the right container.

# **Screenshots**

**Comment by BellCubeDev** [comment]
The Work Room hanging has been a specific issue since an update to Powerofthree's Papyrus Extender.

I've learned a new way to debug looping and hanging scripts recently though, so I might have to try that in a bit.

**Comment by BellCubeDev** [comment]
Forgot to close the issue here!

### BellCube, 15 January 2023
> I believe I might've just pinned down what's been causing the huge hangups - PO3's Papyrus Extender, as of version 5.2.0, appears to be adding items to its arrays per count - for instance, if you were to have a thousand or so gold, it'd add a thousand entries of Gold to the array.
> 
> This, suffice to say, is not ideal. I believe that it's only really noticeable with the Work Room sorting because Gold is considered a Misc. Item, which is what the Work Room sorter looks at.
> Source: powerof3/PapyrusExtenderSSE@a2fac3a2f5b967750a3822004830d4166eb220c4

### BellCube, 15 January 2023
> Got PO3's attention. They plan to revert to the one-entry-per-item model.
>
> [Discord convo (r/skyrimmods server):](https://discord.com/channels/341090804611285003/1011775399774142504/1064358973832179732)
> ![Screenshot of the conversation from the above link](https://i.imgur.com/51LnNqH.png)

### BellCube, 17 January 2023
> I've just added a temporary band-aid patch as a separate file while we wait for PO3 to address the issue on Papyrus Extender's side.

### BellCube, 15 July 2023
> Nobody ever told me that PO3 fixed the issue on Papyrus Extender's side on February 7th (the code change being on the 1st)!
> 
> Thank you to LuciusPortanius24 for pointing this out to me!
> 
> Source: powerof3/PapyrusExtenderSSE@ef819246463f0f765c70476ccff1e2bb1e282e3a
